[package]
name = "sp-mcp"
version = "0.1.0"
edition = "2021"

[lib]
name = "sp_mcp"
path = "src/lib.rs"

[[bin]]
name = "sp-mcp"
path = "src/main.rs"

[dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }
sp-typst = { path = "../sp-typst" }
sp-check = { path = "../sp-check" }
sp-extract = { path = "../sp-extract" }
serde_json = "1"
